Algoritmo de printar lane (única lane, sem cor)
bicanco/SSC0119-2020-1 pull request #3
Opened 2020-05-27 11:50 UTC by gabtoschi

2020-05-27 12:10 UTC, bicanco commented on offsetPrint.asm
> +; static ScreenHeight + #0, #30
Acho que pode apagar essas linhas se não está utilizando elas.

2020-05-27 12:25 UTC, bicanco requested changes
Tem algumas labels que não são chamadas em nenhum lugar, acho que pode deixá-las só como comentários para deixar o código um pouquinho mais limpo.

2020-05-27 12:25 UTC, bicanco commented on offsetPrint.asm
> +; static ScreenHeight + #0, #30
Acho que pode descomentar essas linhas. Quase certeza absoluta que será necessário utilizar isso em outro lugares.

2020-05-27 12:25 UTC, bicanco commented on offsetPrint.asm
> +globalInitLanes:              ; === GLOBALINIT > LANES ===
Por que esta label? Ela não é chamada em nenhum lugar.

2020-05-27 12:25 UTC, bicanco commented on offsetPrint.asm
> +  ; TestLane
Acho que pode apagar este comentário, ou melhorá-lo.

2020-05-27 12:25 UTC, bicanco commented on offsetPrint.asm
> +globalInitEnd:                ; === GLOBALINIT > END ===
Por que esta label? Ela não é chamada em nenhum lugar.

2020-05-27 12:25 UTC, bicanco commented on offsetPrint.asm
> +  rts                         ; return globalInit function
Acho que pode melhorar o comentário dessa linha, talvez "return of globalInit function"

2020-05-27 12:25 UTC, bicanco commented on offsetPrint.asm
> +  push r7
Por que você pula do r4 para o r7?

2020-06-12 18:53 UTC, gabtoschi commented on offsetPrint.asm
> +globalInitLanes:              ; === GLOBALINIT > LANES ===
Eu fiz isso pra ficar mais fácil do Code usar a setinha do lado pra esconder parte de código (meio como a gente faz com {} em códigos normais). Mas posso tirar se quiser.

2020-06-12 18:54 UTC, gabtoschi commented on offsetPrint.asm
> +  push r7
Porque eu não sabia quantos eu ia usar, então eu achei melhor manter o r7 sempre como o meu "registrador temporário" onde usava pra pegar valores que iam ser somados ou comparados com o resto

2020-06-12 18:56 UTC, gabtoschi commented on offsetPrint.asm
> +globalInitEnd:                ; === GLOBALINIT > END ===
Mesma coisa da label de cima.

2020-06-14 19:19 UTC, bicanco approved these changes

2020-06-14 19:20 UTC, merged